name = "Companion ğŸ• (Forge)"
filename = "Companion-1.18-forge-1.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3652/357/Companion-1.18-forge-1.2.0.jar"
hash-format = "murmur2"
hash = "657371351"

[update]
[update.curseforge]
file-id = 3652357
project-id = 559989
