name = "Jade ğŸ”"
filename = "Jade-1.18.1-4.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3662/887/Jade-1.18.1-4.4.0.jar"
hash-format = "murmur2"
hash = "1584043939"

[update]
[update.curseforge]
file-id = 3662887
project-id = 324717
