name = "Jade ğŸ”"
filename = "Jade-1.18.1-4.4.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3681/458/Jade-1.18.1-4.4.1.jar"
hash-format = "murmur2"
hash = "3875290686"

[update]
[update.curseforge]
file-id = 3681449
project-id = 324717
