name = "Jade ğŸ”"
filename = "Jade-1.18.2-5.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3761/542/Jade-1.18.2-5.1.0.jar"
hash-format = "murmur2"
hash = "4039045252"

[update]
[update.curseforge]
file-id = 3761542
project-id = 324717
