name = "Jade ğŸ”"
filename = "Jade-1.18-4.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3636/65/Jade-1.18-4.2.0.jar"
hash-format = "murmur2"
hash = "808200165"

[update]
[update.curseforge]
file-id = 3636065
project-id = 324717
