name = "Jade ğŸ”"
filename = "Jade-1.18-4.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3564/963/Jade-1.18-4.1.0.jar"
hash-format = "murmur2"
hash = "2639870210"

[update]
[update.curseforge]
file-id = 3564963
project-id = 324717
